version: "3.8"
services:
  server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    tty: true
    stdin_open: true
    command: sleep infinity

  client:
    image: python:3.11
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - server
    tty: true
    stdin_open: true
    command: sleep infinity
